travis:
  secure:
    BINSTAR_TOKEN: bGNH497Wr5loPh+VGc6v8T7iuS9rW6V7U9kVavt/4FGpS7vALBWCoxMtkWvy+bB8GS3n3HRY5DWU++eYCgSIzPCbUy0wQfVehlQ0U2hJk3k0v/+b1fxPj4oCcCnjIMURSS0mGW/DKXNtdxy4bfNB2Avnon+ldCvkzfRObu20+kWBjRDnzpG7/Iywpq0qURdSwvbgSNoObSewIg8TL6kxhUcrH94/Re3JmCfGWfIeWZUHFvWdeUgQ0Mdn6sOol/jCGqI+JGcKELLl/tAFjl1+JAh5BMtUigJmZM79fjxaNsJFEoT/dryE2Z6a+GZnEzfEl8Vyytov6HTXThEu65BxMrZqH4NGRS50fQXjEXnvUCQVAV9IcCpu4xzHkb146fNLmtkzcBpK1aM7rjZdHX8R5gwFWyMSNecH6Ja30iKzn1/SY8H0Xi/bFEBI9W38YoyEQZh7/mgJUl/2JLUo3qtX44h+O5s/hR8PMjioJijMVaJN18YB8M831M2vX7GdD4BsBj8p0O4yXL86o43B8xxnEjhfCdaNhy6D/lMeup2PDbLmu2cC4+TDEKvayLJNA1AfOiN7u6sFlL7fGS5aG61DFTPIQwOxSxyZzRISnw5vcXNII8qOgD/Apq0gxgVnXtq8YCuAzVKJherp6K5c+Z6bAKyf+aYWuxblUWFHkIelHFU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
